# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'TCO14' do
pod 'SDWebImage', '~> 3.7'
pod 'ASIHTTPRequest', '~> 1.8'
end

target 'TCO14Tests' do

end

